/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as PageRouteImport } from './routes/page';
import { Route as AboutPageRouteImport } from './routes/about/page';

const PageRoute = PageRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const AboutPageRoute = AboutPageRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof PageRoute;
  '/about/': typeof AboutPageRoute;
}
export interface FileRoutesByTo {
  '/': typeof PageRoute;
  '/about': typeof AboutPageRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof PageRoute;
  '/about/': typeof AboutPageRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/about/';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/about';
  id: '__root__' | '/' | '/about/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  PageRoute: typeof PageRoute;
  AboutPageRoute: typeof AboutPageRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof PageRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/about/': {
      id: '/about/';
      path: '/about';
      fullPath: '/about/';
      preLoaderRoute: typeof AboutPageRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  PageRoute: PageRoute,
  AboutPageRoute: AboutPageRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
